### PR TITLE
Update to use Maven Annotations

### PR DESCRIPTION
**Pull request by hazendaz**

### CODE REVIEW

**Comment by lukaszlenart** [comment]
Because of the `org.eclipse.m2e` plugin there is a lot of warnings now :(
```
[WARNING] The POM for org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for org.eclipse.m2e:lifecycle-mapping:1.0.0: Plugin org.eclipse.m2e:lifecycle-mapping:1.0.0 or one of its dependencies could not be resolved: Failure to find org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 in http://uk.maven.org/maven2/ was cached in the local repository, resolution will not be reattempted until the update interval of uk has elapsed or updates are forced
[WARNING] The POM for org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for org.eclipse.m2e:lifecycle-mapping:1.0.0: Plugin org.eclipse.m2e:lifecycle-mapping:1.0.0 or one of its dependencies could not be resolved: Failure to find org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 in http://uk.maven.org/maven2/ was cached in the local repository, resolution will not be reattempted until the update interval of uk has elapsed or updates are forced
```

**Comment by hazendaz** [comment]
Very strange.  I do not believe I have seen that one before as an issue.  Have you tried deleting that item from your local .m2/repository and trying again?  If that doesn't end up helping that plugin is 100% safe to delete.  All it does more or less is remove other warnings about life cycle issues which in turn can be modified to ignore anyways in eclipse.

--- Original Message ---

**Comment by lukaszlenart** [comment]
try `mvn clean source:jar` - it happens only during release

**Comment by hazendaz** [comment]
This can be ignored but if you want to delve farther, I found this http://stackoverflow.com/questions/7905501/get-rid-of-pom-not-found-warning-for-org-eclipse-m2elifecycle-mapping

**Comment by lukaszlenart** [comment]
Thanks! Moved the plugin into a profile

**Pull request merged**
