### PR TITLE
Update maven wrapper, use relativePath to force .m2 lookup for the oss-parent, and full maven 3

### PR DESCRIPTION
**Pull request by hazendaz**

### CODE REVIEW

**Comment by hazendaz** [comment]
@lukaszlenart This will replace #115.  Since there are no unit tests currently or integration tests to confirm the plugin works and I don't have any working sample usage at home, this will need a test on your end to confirm nothing is actually broken.  Once confirmed working and this comes in, maven 2 is dropped entirely.

**Comment by hazendaz** [comment]
@lukaszlenart I should note, I followed same logic I have in a plugin I support that went from maven 2 to 3 a while back (spotbugs-maven-plugin).  Overall it's trivial but a true IT test within this project would really help confirm things work as expected ;)

**Comment by lukaszlenart** [comment]
Thanks for helping with this! 

> Re:  IT test

Yes I know that it would be nice to have them but as always it's a matter of spare time :)

**Comment by hazendaz** [comment]
Thanks!  One day if I find the time I'll add some ITs.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request merged**
